export const users = [
  {
    name: "Walter White",
    jobTitle: "Chemistry Specialist",
    description:
      "Former high school chemistry teacher with extensive knowledge in chemical processes and pharmaceutical development.",
    personalImg:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRfNjUepcJE63cHgBtiaamPY5bP9-EQ3l0S7w&s",
    socialMedia: {
      facebook: "https://facebook.com/walter.white",
      instagram: "https://instagram.com/walter_chemistry",
      linkedin: "https://linkedin.com/in/walter-white-chemistry",
      twitter: "https://twitter.com/walter_chem",
      youtube: "https://youtube.com/@WalterChemistry",
    },
    isPremium: true,
  },
  ,
  {
    name: "Chisom Chukwukwe",
    jobTitle: "UI/UX Designer",
    description:
      "Hardworking and reliable UI/UX designer focused on going above and beyond to support teams and serve customers.",
    personalImg: "https://randomuser.me/api/portraits/women/1.jpg",
    socialMedia: {
      facebook: "https://facebook.com/chisom.chukwukwe",
      instagram: "https://instagram.com/chisom_designs",
      linkedin: "https://linkedin.com/in/chisom-chukwukwe",
      twitter: "https://twitter.com/chisom_ux",
      youtube: "https://youtube.com/@ChisomDesigns",
    },
  },
  {
    name: "John Doe",
    jobTitle: "Software Engineer",
    description:
      "Passionate about coding and always eager to learn new technologies.",
    personalImg: "https://randomuser.me/api/portraits/men/2.jpg",
    socialMedia: {
      facebook: "https://facebook.com/john.doe.dev",
      instagram: "https://instagram.com/johndoe_codes",
      linkedin: "https://linkedin.com/in/john-doe-engineer",
      twitter: "https://twitter.com/johndoe_dev",
      youtube: "https://youtube.com/@JohnDoeCode",
    },
  },
  {
    name: "Jane Smith",
    jobTitle: "Product Manager",
    description:
      "Experienced in leading cross-functional teams to deliver high-quality products.",
    personalImg: "https://randomuser.me/api/portraits/women/3.jpg",
    socialMedia: {
      facebook: "https://facebook.com/jane.smith.pm",
      instagram: "https://instagram.com/janesmith_pm",
      linkedin: "https://linkedin.com/in/jane-smith-product",
      twitter: "https://twitter.com/janesmith_pm",
      youtube: "https://youtube.com/@JaneSmithProduct",
    },
  },
  {
    name: "Alice Johnson",
    jobTitle: "Data Scientist",
    description:
      "Skilled in data analysis and machine learning, with a passion for turning data into actionable insights.",
    personalImg: "https://randomuser.me/api/portraits/women/4.jpg",
    socialMedia: {
      facebook: "https://facebook.com/alice.johnson.data",
      instagram: "https://instagram.com/alice_datascience",
      linkedin: "https://linkedin.com/in/alice-johnson-data",
      twitter: "https://twitter.com/alice_data",
      youtube: "https://youtube.com/@AliceDataScience",
    },
  },
  {
    name: "Michael Brown",
    jobTitle: "DevOps Engineer",
    description: "Expert in cloud infrastructure and automation tools.",
    personalImg: "https://randomuser.me/api/portraits/men/5.jpg",
    socialMedia: {
      facebook: "https://facebook.com/michael.brown.devops",
      instagram: "https://instagram.com/mike_devops",
      linkedin: "https://linkedin.com/in/michael-brown-devops",
      twitter: "https://twitter.com/mike_devops",
      youtube: "https://youtube.com/@MikeDevOps",
    },
  },
  {
    name: "Emily Davis",
    jobTitle: "Frontend Developer",
    description: "Loves building beautiful and responsive web interfaces.",
    personalImg: "https://randomuser.me/api/portraits/women/6.jpg",
    socialMedia: {
      facebook: "https://facebook.com/emily.davis.frontend",
      instagram: "https://instagram.com/emily_frontend",
      linkedin: "https://linkedin.com/in/emily-davis-frontend",
      twitter: "https://twitter.com/emily_codes",
      youtube: "https://youtube.com/@EmilyFrontend",
    },
  },
  {
    name: "David Wilson",
    jobTitle: "Backend Developer",
    description:
      "Enjoys solving complex problems and optimizing server performance.",
    personalImg: "https://randomuser.me/api/portraits/men/7.jpg",
    socialMedia: {
      facebook: "https://facebook.com/david.wilson.backend",
      instagram: "https://instagram.com/david_backend",
      linkedin: "https://linkedin.com/in/david-wilson-backend",
      twitter: "https://twitter.com/david_backend",
      youtube: "https://youtube.com/@DavidBackend",
    },
  },
  {
    name: "Sophia Martinez",
    jobTitle: "QA Engineer",
    description: "Detail-oriented tester ensuring bug-free releases.",
    personalImg: "https://randomuser.me/api/portraits/women/8.jpg",
    socialMedia: {
      facebook: "https://facebook.com/sophia.martinez.qa",
      instagram: "https://instagram.com/sophia_testing",
      linkedin: "https://linkedin.com/in/sophia-martinez-qa",
      twitter: "https://twitter.com/sophia_qa",
      youtube: "https://youtube.com/@SophiaQA",
    },
  },
  {
    name: "James Anderson",
    jobTitle: "Mobile Developer",
    description: "Building seamless mobile experiences for iOS and Android.",
    personalImg: "https://randomuser.me/api/portraits/men/9.jpg",
    socialMedia: {
      facebook: "https://facebook.com/james.anderson.mobile",
      instagram: "https://instagram.com/james_mobile",
      linkedin: "https://linkedin.com/in/james-anderson-mobile",
      twitter: "https://twitter.com/james_mobile",
      youtube: "https://youtube.com/@JamesMobile",
    },
  },
  {
    name: "Olivia Thomas",
    jobTitle: "Scrum Master",
    description: "Facilitates agile teams and removes impediments.",
    personalImg: "https://randomuser.me/api/portraits/women/10.jpg",
    socialMedia: {
      facebook: "https://facebook.com/olivia.thomas.scrum",
      instagram: "https://instagram.com/olivia_agile",
      linkedin: "https://linkedin.com/in/olivia-thomas-scrum",
      twitter: "https://twitter.com/olivia_scrum",
      youtube: "https://youtube.com/@OliviaAgile",
    },
  },
  {
    name: "Benjamin Lee",
    jobTitle: "Full Stack Developer",
    description:
      "Versatile developer comfortable with both frontend and backend.",
    personalImg: "https://randomuser.me/api/portraits/men/11.jpg",
    socialMedia: {
      facebook: "https://facebook.com/benjamin.lee.fullstack",
      instagram: "https://instagram.com/ben_fullstack",
      linkedin: "https://linkedin.com/in/benjamin-lee-fullstack",
      twitter: "https://twitter.com/ben_fullstack",
      youtube: "https://youtube.com/@BenFullStack",
    },
  },
  {
    name: "Mia Harris",
    jobTitle: "Graphic Designer",
    description: "Creates stunning visuals and brand identities.",
    personalImg: "https://randomuser.me/api/portraits/women/12.jpg",
    socialMedia: {
      facebook: "https://facebook.com/mia.harris.design",
      instagram: "https://instagram.com/mia_designs",
      linkedin: "https://linkedin.com/in/mia-harris-design",
      twitter: "https://twitter.com/mia_design",
      youtube: "https://youtube.com/@MiaDesigns",
    },
  },
  {
    name: "William Clark",
    jobTitle: "System Administrator",
    description: "Keeps systems running smoothly and securely.",
    personalImg: "https://randomuser.me/api/portraits/men/13.jpg",
    socialMedia: {
      facebook: "https://facebook.com/william.clark.sysadmin",
      instagram: "https://instagram.com/will_sysadmin",
      linkedin: "https://linkedin.com/in/william-clark-sysadmin",
      twitter: "https://twitter.com/will_sysadmin",
      youtube: "https://youtube.com/@WillSysAdmin",
    },
  },
  {
    name: "Charlotte Lewis",
    jobTitle: "Content Strategist",
    description: "Crafts compelling content strategies for digital platforms.",
    personalImg: "https://randomuser.me/api/portraits/women/14.jpg",
    socialMedia: {
      facebook: "https://facebook.com/charlotte.lewis.content",
      instagram: "https://instagram.com/charlotte_content",
      linkedin: "https://linkedin.com/in/charlotte-lewis-content",
      twitter: "https://twitter.com/charlotte_content",
      youtube: "https://youtube.com/@CharlotteContent",
    },
  },
  {
    name: "Henry Walker",
    jobTitle: "Security Analyst",
    description: "Protects data and systems from cyber threats.",
    personalImg: "https://randomuser.me/api/portraits/men/15.jpg",
    socialMedia: {
      facebook: "https://facebook.com/henry.walker.security",
      instagram: "https://instagram.com/henry_security",
      linkedin: "https://linkedin.com/in/henry-walker-security",
      twitter: "https://twitter.com/henry_security",
      youtube: "https://youtube.com/@HenrySecurity",
    },
  },
  {
    name: "Amelia Hall",
    jobTitle: "Marketing Specialist",
    description: "Drives user engagement through creative campaigns.",
    personalImg: "https://randomuser.me/api/portraits/women/16.jpg",
    socialMedia: {
      facebook: "https://facebook.com/amelia.hall.marketing",
      instagram: "https://instagram.com/amelia_marketing",
      linkedin: "https://linkedin.com/in/amelia-hall-marketing",
      twitter: "https://twitter.com/amelia_marketing",
      youtube: "https://youtube.com/@AmeliaMarketing",
    },
  },
  {
    name: "Alexander Young",
    jobTitle: "Business Analyst",
    description: "Analyzes business needs and recommends solutions.",
    personalImg: "https://randomuser.me/api/portraits/men/17.jpg",
    socialMedia: {
      facebook: "https://facebook.com/alexander.young.ba",
      instagram: "https://instagram.com/alex_business",
      linkedin: "https://linkedin.com/in/alexander-young-ba",
      twitter: "https://twitter.com/alex_business",
      youtube: "https://youtube.com/@AlexBusiness",
    },
  },
  {
    name: "Evelyn King",
    jobTitle: "Support Engineer",
    description: "Helps customers resolve technical issues quickly.",
    personalImg: "https://randomuser.me/api/portraits/women/18.jpg",
    socialMedia: {
      facebook: "https://facebook.com/evelyn.king.support",
      instagram: "https://instagram.com/evelyn_support",
      linkedin: "https://linkedin.com/in/evelyn-king-support",
      twitter: "https://twitter.com/evelyn_support",
      youtube: "https://youtube.com/@EvelynSupport",
    },
  },
  {
    name: "Daniel Wright",
    jobTitle: "AI Engineer",
    description: "Develops intelligent systems and machine learning models.",
    personalImg: "https://randomuser.me/api/portraits/men/19.jpg",
    socialMedia: {
      facebook: "https://facebook.com/daniel.wright.ai",
      instagram: "https://instagram.com/daniel_ai",
      linkedin: "https://linkedin.com/in/daniel-wright-ai",
      twitter: "https://twitter.com/daniel_ai",
      youtube: "https://youtube.com/@DanielAI",
    },
  },
  {
    name: "Grace Scott",
    jobTitle: "Project Manager",
    description: "Leads projects from conception to delivery.",
    personalImg: "https://randomuser.me/api/portraits/women/20.jpg",
    socialMedia: {
      facebook: "https://facebook.com/grace.scott.pm",
      instagram: "https://instagram.com/grace_projects",
      linkedin: "https://linkedin.com/in/grace-scott-pm",
      twitter: "https://twitter.com/grace_pm",
      youtube: "https://youtube.com/@GraceProjects",
    },
  },
];
